package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// Event 表示一个待生成的 C# 表项。
type Event interface {
	isEvent()
}

// GroupEvent 表示头文件中的注释分组。
type GroupEvent struct {
	text string
}

// SignalEvent 表示头文件中的信号定义。
type SignalEvent struct {
	signal Signal
}

func (GroupEvent) isEvent() {}

func (SignalEvent) isEvent() {}

// Signal 保存解析后的宏名称、宏值、注释和 C# 类型。
type Signal struct {
	name       string
	value      any
	comment    string
	signalType string
}

// ParserState 保存头文件元信息，以及按源码顺序解析出的事件。
type ParserState struct {
	version string
	date    string
	events  []Event
}

// scanHeader 解析输入头文件，并返回解析出的元信息和信号。
func scanHeader(path string) (ParserState, int, error) {
	log.Println("正在解析头文件..")

	state := ParserState{}
	parseCount := 0

	file, err := os.Open(path)
	if err != nil {
		return ParserState{}, 0, fmt.Errorf("打开头文件失败: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)

	isBody := false

	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := scanner.Text()
		trimLine := strings.TrimSpace(line)

		if trimLine == "" {
			continue
		}

		if strings.HasPrefix(trimLine, "namespace") {
			if state.version == "" {
				return ParserState{}, 0, fmt.Errorf("未解析到版本号")
			}

			if state.date == "" {
				return ParserState{}, 0, fmt.Errorf("未解析到更新时间")
			}

			isBody = true
			continue
		}

		if !isBody {

			if strings.Contains(trimLine, "Version") {
				err := state.parseVersion(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf("第 %d 行: %s: 解析版本号错误: %w", lineNo, trimLine, err)
				}
				continue
			}

			if strings.Contains(trimLine, "Date") {
				err := state.parseDate(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf("第 %d 行: %s: 解析更新时间失败: %w", lineNo, trimLine, err)
				}
				continue
			}

		} else {

			if strings.HasPrefix(trimLine, "//") {
				err := state.parseGroup(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf("第 %d 行: %s: 解析信号组失败: %w", lineNo, trimLine, err)
				}
				continue
			}

			if strings.HasPrefix(trimLine, "#define") {
				err := state.parseSignal(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf("第 %d 行: %s: 解析信号失败: %w", lineNo, trimLine, err)
				}
				parseCount++
				continue
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return ParserState{}, 0, fmt.Errorf("读取头文件失败: %w", err)
	}

	if state.version == "" {
		return ParserState{}, 0, fmt.Errorf("未解析到版本号")
	}

	if state.date == "" {
		return ParserState{}, 0, fmt.Errorf("未解析到更新时间")
	}

	if parseCount == 0 {
		return ParserState{}, 0, fmt.Errorf("未解析到任何信号")
	}

	return state, parseCount, nil
}

// writeCSharpFile 将生成的 C# 信号表写入 outputPath。
func writeCSharpFile(outputPath string, state ParserState) (err error) {
	log.Println("正在生成目标文件..")

	file, err := os.Create(filepath.Join(outputPath, "VehicleSignalTable.cs"))
	if err != nil {
		return fmt.Errorf("创建文件失败: %w", err)
	}
	defer func() {
		if closeErr := file.Close(); err == nil && closeErr != nil {
			err = fmt.Errorf("关闭文件失败: %w", closeErr)
		}
	}()

	writeLine := func(format string, args ...any) error {
		var err error
		if len(args) == 0 {
			_, err = fmt.Fprintln(file, format)
		} else {
			_, err = fmt.Fprintf(file, format+"\n", args...)
		}
		if err != nil {
			return fmt.Errorf("写入文件失败: %w", err)
		}
		return nil
	}

	headerLines := []string{
		"// <auto-generated>",
		"// Generated from CLUSTER_HMI_IF.h. Do not edit manually.",
		fmt.Sprintf("// Version: %s", state.version),
		fmt.Sprintf("// Date: %s", state.date),
		"// </auto-generated>",
		"",
		"namespace Data",
		"{",
		"\tpublic static class VehicleSignalTable",
		"\t{",
	}

	for _, line := range headerLines {
		if err := writeLine(line); err != nil {
			return err
		}
	}

	for _, event := range state.events {
		switch e := event.(type) {
		case GroupEvent:
			if e.text != "" {
				if err := writeLine(""); err != nil {
					return err
				}
				if err := writeLine("\t\t/* ========== %s ========== */", e.text); err != nil {
					return err
				}
				if err := writeLine(""); err != nil {
					return err
				}
			}

		case SignalEvent:
			if err := writeLine("\t\t// %s", e.signal.comment); err != nil {
				return err
			}
			if err := writeLine("\t\tpublic const %s %s = %s;", e.signal.signalType, e.signal.name, e.signal.value); err != nil {
				return err
			}
			if err := writeLine(""); err != nil {
				return err
			}
		}
	}

	if err := writeLine("\t}"); err != nil {
		return err
	}
	if err := writeLine("}"); err != nil {
		return err
	}

	return nil
}

// parseVersion 从头文件元信息行中提取版本号。
func (p *ParserState) parseVersion(line string) error {
	if p.version != "" {
		return fmt.Errorf("解析到重复文本")
	}

	index := strings.Index(line, ":")
	if index < 0 {
		return fmt.Errorf("未识别到 ':' 符号")
	}

	version := strings.TrimSpace(line[index+1:])
	if version == "" {
		return fmt.Errorf("解析为空")
	}

	p.version = version

	return nil
}

// parseDate 从头文件元信息行中提取更新时间。
func (p *ParserState) parseDate(line string) error {
	if p.date != "" {
		return fmt.Errorf("解析到重复文本")
	}

	index := strings.Index(line, ":")
	if index < 0 {
		return fmt.Errorf("未识别到 ':'")
	}

	date := strings.TrimSpace(line[index+1:])
	if date == "" {
		return fmt.Errorf("解析为空")
	}

	p.date = date

	return nil
}

// parseGroup 解析注释分组，并追加为分组事件。
func (p *ParserState) parseGroup(line string) error {
	group := strings.TrimSpace(strings.TrimPrefix(line, "//"))
	if group == "" {
		return fmt.Errorf("解析为空")
	}

	p.events = append(p.events, GroupEvent{text: group})

	return nil
}

// parseSignal 从 #define 行解析信号，并追加为信号事件。
func (p *ParserState) parseSignal(line string) error {

	rest := strings.TrimSpace(strings.TrimPrefix(line, "#define"))

	defineText, after, ok := strings.Cut(rest, "//")
	if !ok {
		defineText = rest
	} else {
		after = strings.TrimSpace(after)
	}

	fields := strings.Fields(defineText)

	signalType := "uint"

	if len(fields) < 2 {
		return fmt.Errorf("格式异常")
	}

	if strings.HasPrefix(fields[1], "\"") {
		signalType = "string"
	}

	signal := Signal{
		name:       fields[0],
		value:      fields[1],
		comment:    after,
		signalType: signalType,
	}

	p.events = append(p.events, SignalEvent{signal})

	return nil
}

func main() {
	log.SetFlags(0)

	inputPath := flag.String("i", "", "输入要解析的头文件的文件路径`路径`")
	outputPath := flag.String("o", "./", "目标文件的生成路径`路径`")

	flag.Parse()

	if *inputPath == "" {
		flag.Usage()
		os.Exit(1)
	}

	state, parseCount, err := scanHeader(*inputPath)
	if err != nil {
		log.Fatal(err)
	}

	if err := writeCSharpFile(*outputPath, state); err != nil {
		log.Fatal(err)
	}

	log.Println("目标文件生成成功")
	log.Println("信号数量: ", parseCount)
}
