package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"strings"
)

type Event interface {
	isEvent()
}

type GroupEvent struct {
	text string
}

type SignalEvent struct {
	signal Signal
}

func (GroupEvent) isEvent() {}

func (SignalEvent) isEvent() {}

type Signal struct {
	name       string
	value      any
	comment    string
	signalType string
}

type ParserState struct {
	version string
	date    string
	events  []Event
}

func scanHeader(path string) (ParserState, int, error) {
	fmt.Println("正在解析头文件..")

	state := ParserState{}
	parseCount := 0

	// 打开文件
	file, err := os.Open(path)
	if err != nil {
		return ParserState{}, 0, fmt.Errorf("打开头文件失败: %s", err)
	}
	defer file.Close()

	// 扫描文件
	scanner := bufio.NewScanner(file)
	if scanner == nil {
		return ParserState{}, 0, fmt.Errorf("扫描头文件失败")
	}

	isBody := false

	// 扫描.h文件，提取出信息
	for scanner.Scan() {
		line := scanner.Text()
		trimLine := strings.TrimSpace(line)

		if trimLine == "" {
			continue
		}

		if strings.HasPrefix(trimLine, "namespace") {
			isBody = true
			continue
		}

		if !isBody {

			if strings.Contains(trimLine, "Version") {
				err := state.parseVersion(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf(trimLine, "解析版本号错误: %s", err)
				}
				continue
			}

			if strings.Contains(trimLine, "Date") {
				err := state.parseDate(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf(trimLine, "解析更新时间失败: %s", err)
				}
				continue
			}

		} else {

			if strings.HasPrefix(trimLine, "//") {
				err := state.parseGroup(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf(trimLine, "解析信号组失败: %s", err)
				}
				continue
			}

			if strings.HasPrefix(trimLine, "#define") {
				err := state.parseSignal(trimLine)
				if err != nil {
					return ParserState{}, 0, fmt.Errorf(trimLine, "解析信号失败: %s", err)
				}
				parseCount++
				continue
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return ParserState{}, 0, fmt.Errorf("读取头文件失败: %s", err)
	}

	return state, parseCount, nil
}

func writeCSharpFile(outputPath string, state ParserState) error {
	fmt.Println("正在生成目标文件..")
	// 创建成果物
	file, err := os.Create(outputPath + "/VehicleSignalTable.cs")
	if err != nil {
		return fmt.Errorf("创建文件失败: %s", err)
	}

	fmt.Fprintln(file, "// <auto-generated>")
	fmt.Fprintln(file, "// Generated from CLUSTER_HMI_IF.h. Do not edit manually.")
	fmt.Fprintln(file, "// Version: ", state.version)
	fmt.Fprintln(file, "// Date: ", state.date)
	fmt.Fprintln(file, "// </auto-generated>")
	fmt.Fprintln(file)
	fmt.Fprintln(file, "namespace Data")
	fmt.Fprintln(file, "{")
	fmt.Fprintln(file, "\tpublic static class VehicleSignalTable")
	fmt.Fprintln(file, "\t{")

	for _, event := range state.events {
		switch e := event.(type) {
		case GroupEvent:
			if e.text != "" {
				fmt.Fprintln(file)
				fmt.Fprintf(file, "\t\t/* ========== %s ========== */\n", e.text)
				fmt.Fprintln(file)
			}

		case SignalEvent:
			fmt.Fprintf(file, "\t\t// %s\n", e.signal.comment)
			fmt.Fprintf(file, "\t\tpublic const %s %s = %s;\n", e.signal.signalType, e.signal.name, e.signal.value)
			fmt.Fprintln(file)
		}
	}

	fmt.Fprintln(file, "\t}")
	fmt.Fprintln(file, "}")

	if err := file.Close(); err != nil {
		return fmt.Errorf("关闭文件失败: %w", err)
	}

	return nil
}

// 版本解析器，提取版本号
func (p *ParserState) parseVersion(line string) error {
	if p.version != "" {
		return fmt.Errorf("解析到重复文本")
	}

	index := strings.Index(line, ":")
	if index < 0 {
		return fmt.Errorf("未识别到 ':' 符号")
	}

	version := strings.TrimSpace(line[index+1:])
	if version == "" {
		return fmt.Errorf("解析为空")
	}

	p.version = version

	return nil
}

// 修改时间解析器
func (p *ParserState) parseDate(line string) error {
	if p.date != "" {
		return fmt.Errorf("解析到重复文本")
	}

	index := strings.Index(line, ":")
	if index < 0 {
		return fmt.Errorf("未识别到 ':'")
	}

	date := strings.TrimSpace(line[index+1:])
	if date == "" {
		return fmt.Errorf("解析为空")
	}

	p.date = date

	return nil
}

// 分组解析器
func (p *ParserState) parseGroup(line string) error {
	group := strings.TrimSpace(strings.TrimPrefix(line, "//"))
	if group == "" {
		return fmt.Errorf("解析为空")
	}

	p.events = append(p.events, GroupEvent{text: group})

	return nil
}

// 信号解析器
func (p *ParserState) parseSignal(line string) error {

	// 去掉宏定义字段
	rest := strings.TrimSpace(strings.TrimPrefix(line, "#define"))

	// 找到 "//" 之后的字段（信号说明）
	_, after, _ := strings.Cut(rest, "//")

	// 分割字符串
	fields := strings.Fields(rest)

	signalType := "uint"

	if len(fields) < 2 {
		return fmt.Errorf("格式异常")
	}

	if strings.HasPrefix(fields[1], "\"") {
		signalType = "string"
	}

	signal := Signal{
		name:       fields[0],
		value:      fields[1],
		comment:    after,
		signalType: signalType,
	}

	p.events = append(p.events, SignalEvent{signal})

	return nil
}

func main() {

	// 解析参数
	inputPath := flag.String("i", "", "输入要解析的头文件的文件路径`路径`")
	outputPath := flag.String("o", "./", "目标文件的生成路径`路径`")

	flag.Parse()

	if *inputPath == "" {
		flag.Usage()
		os.Exit(1)
	}

	// 解析头文件
	state, parseCount, err := scanHeader(*inputPath)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// 生成目标文件
	if err := writeCSharpFile(*outputPath, state); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println("目标文件生成成功")
	fmt.Println("信号数量: ", parseCount)
}
